name       : libxfce4util
version    : 4.12.1
release    : 1
source     :
    - http://archive.xfce.org/src/xfce/libxfce4util/4.12/libxfce4util-4.12.1.tar.bz2 : 876bdefa2e13cbf68b626b2158892fb93e824e1ef59cf951123a96cefbc8881d
license    : GPL-2.0
summary    : XFCE4 Utilities
description: |
    XFCE4 Utilities
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
