name       : libxfce4util
version    : 4.17.2
release    : 4
source     :
    - https://archive.xfce.org/src/xfce/libxfce4util/4.17/libxfce4util-4.17.2.tar.bz2 : cf5f4095ffa8ebe3d819ac779768cb75c567a85d5a508a4c4713258c1bd0fab7
homepage   : https://docs.xfce.org/xfce/libxfce4util/start
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Extension library for Xfce
description: |
    Libxfce4util is used to share commonly used non-GTK+ utilities among the Xfce applications.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
